name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  Test:
    runs-on: macOS-latest
    steps:
    
#     - name: Setup environment variables
#       run: |
#         export PROJECT_PATH=$(find ./ -name "*.xcodeproj");
#         export PROJECT_NAME=$(basename "${PROJECT_PATH%.*}"); \
#         export SCHEME_PATH=$(find $PROJECT_PATH -name "$PROJECT_NAME.xcscheme")

    - uses: actions/checkout@v1
        
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
#     - name: Select Xcode
#       run: sudo xcode-select -switch /Applications/Xcode_12.5.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: |
        export PROJECT_PATH=$(find ./ -name "*.xcodeproj"); \
        export PROJECT_NAME=$(basename "${PROJECT_PATH%.*}"); \
        export SCHEME_PATH=$(find $PROJECT_PATH -name "$PROJECT_NAME.xcscheme"); \
        ls -l; echo $PROJECT_NAME; echo $PROJECT_PATH; \
        
        xcodebuild test \
        -scheme $PROJECT_NAME \
        -project $PROJECT_PATH \
        -destination 'platform:iOS Simulator, OS:15.2, name:iPhone 12 Pro Max' \
        | xcpretty && exit ${PIPESTATUS[0]}

        
