name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
#     - name: Install GPG
#       run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
#     - name: Decrypt large secret
#       run: ./provisioning/import_provisioning.sh
#       env:
#         PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.5.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: |
        # gets project path, name and path to all schemes in the project
        PROJECT_PATH=$(find ./ -name "*.xcodeproj")
        PROJECT_NAME=$(basename "${PROJECT_PATH%.*}")
        SCHEME_PATH=$(find $PROJECT_PATH -name "$PROJECT_NAME.xcscheme")
        ls -l; echo $PROJECT_NAME; echo $PROJECT_PATH
        
        xcodebuild test \
        -scheme $PROJECT_NAME \
        -project $PROJECT_PATH \
        -destination "platform=iOS Simulator,name=iPhone 8"\
        | xcpretty && exit ${PIPESTATUS[0]}

        xcodebuild \
        -sdk iphoneos \
        -project $PROJECT_PATH \
        -configuration Release \
        -scheme $PROJECT_NAME \
        -derivedDataPath DerivedData \
        -archivePath DerivedData/Archive/${PROJECT_NAME} archive;
        ls -lR
    - name: Export Archive
      run: ls -lR; xcodebuild -exportArchive -archivePath DerivedData/Archive/CocoaHeadsNL.xcarchive -exportOptionsPlist provisioning/App-Store.plist -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
#     - name: Deploy App to Apple
#       run: xcrun altool --upload-app --type ios --file DerivedData/ipa/CocoaHeadsNL.ipa --username "${{ secrets.appstore_connect_username }}" --password "${{ secrets.appstore_connect_password }}" --verbose
