name: xcode-test

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  workflow_dispatch:

jobs:
  TestJob:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: step1
        run: export FOO='bar' >> $GITHUB_ENV
      
      - name: step2
        run: "echo var1 equals: ${{ env.FOO }}" 
